version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: mysql://root:superadmin@tcp(db:3306)/elpempek
    depends_on:
      - db

  db:
    image: mysql:8.0.33
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: superadmin
      MYSQL_DATABASE: elpempek
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql   # Persistent local volume

# Local named volume (not needed since we're using a bind mount)
# You can remove this unless you’re using PostgreSQL elsewhere
# volumes:
#   pgdata:
